version: '3.7'
services:
  xnat-web:
    image: somnonetz/snet-xnat
    container_name: xnat-web
    environment:
      CATALINA_OPTS: -Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      XNAT_VERSION: ${XNAT_VERSION}
      XNAT_SMTP_ENABLED: ${XNAT_SMTP_ENABLED}
      XNAT_SMTP_HOSTNAME: ${XNAT_SMTP_HOSTNAME}
      XNAT_SMTP_PORT: ${XNAT_SMTP_PORT}
      XNAT_SMTP_AUTH: ${XNAT_SMTP_AUTH}
      XNAT_SMTP_USERNAME: ${XNAT_SMTP_USERNAME}
      XNAT_SMTP_PASSWORD: ${XNAT_SMTP_PASSWORD}
      XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
      XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
      XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
      XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
      TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
      PGPASSWORD: ${XNAT_DATASOURCE_PASSWORD}
      XNAT_ROOT: ${XNAT_ROOT}
      XNAT_HOME: ${XNAT_HOME}
      XNAT_EMAIL: ${XNAT_EMAIL}
      XNAT_API_URL: ${XNAT_API_URL}
      VIRTUAL_HOST: ${XNAT_HOST}
      VIRTUAL_PORT: 8080
    expose:
      - "8080"
    ports:
      - "8104:8104"
    volumes:
      - ./xnat-data/home/logs:${XNAT_HOME}/logs
      - ./xnat-data/archive:${XNAT_ROOT}/archive
      - ./xnat-data/build:${XNAT_ROOT}/build
      - ./xnat-data/cache:${XNAT_ROOT}/cache
      # - ../copla-editor/sn-editor/build:/usr/local/tomcat/webapps/sn-editor
      # - ../snet-plugin/build/libs/snet-plugin-0.1.9.jar:/data/xnat/home/plugins/snet-plugin-0.1.9.jar
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    networks:
      - snet-apps

  xnat-db:
    image: postgres:12.7-alpine
    container_name: xnat-db
    environment:
      POSTGRES_USER: ${XNAT_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${XNAT_DATASOURCE_DBNAME}
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - snet-apps

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - ./nginx-proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - snet-apps
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=bowden@htw-berlin.de
    networks:
      - snet-asclepios

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  snet-apps:
    driver: bridge
    name: snet-apps
